import React, { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { Navigate, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useLanguage } from '../contexts/LanguageContext';
import { useTheme } from '../contexts/ThemeContext';
import { IconUser, IconSun, IconMoon } from '../components/Icons';

const BENEFITS = [
  {
    icon: '📈',
    ja_title: 'キャリアアップ',
    en_title: 'Career Advancement',
    ja_desc: 'AWS認定取得者は採用市場での評価が高く、年収アップにも直結しやすい世界標準の資格です。',
    en_desc: 'AWS certifications are globally recognized and often lead to higher salaries and better job opportunities.',
  },
  {
    icon: '✅',
    ja_title: 'スキルの客観的証明',
    en_title: 'Validated Cloud Skills',
    ja_desc: 'クラウドの実践スキルをAmazon公認の試験で証明。エンジニアとしての信頼性を高めます。',
    en_desc: 'Demonstrate your cloud expertise with an Amazon-recognized credential that validates your real-world skills.',
  },
  {
    icon: '🏗️',
    ja_title: '実務で使える知識',
    en_title: 'Practical Knowledge',
    ja_desc: '試験対策を通じてアーキテクチャ設計・セキュリティ・コスト最適化など実務直結の知識が定着します。',
    en_desc: 'Study for the exam and gain practical knowledge in architecture, security, and cost optimization.',
  },
  {
    icon: '🎯',
    ja_title: 'CLFからProまで全12種',
    en_title: '12 Certifications',
    ja_desc: '入門向けのCLFからアソシエイト・プロフェッショナル・スペシャリティまで体系的に学習できます。',
    en_desc: 'From foundational CLF to associate, professional, and specialty levels — all 12 certifications covered.',
  },
];

const FEATURES = [
  {
    icon: '🤖',
    ja_title: 'AI生成の高品質問題',
    en_title: 'AI-Generated Questions',
    ja_desc: 'Claude AIが作成した本番試験同等の問題を2,600問以上収録。解説・選択肢別解説付きで理解が深まります。',
    en_desc: 'Over 2,600 exam-quality questions generated by Claude AI, with detailed explanations for every choice.',
  },
  {
    icon: '📚',
    ja_title: '3つの学習モード',
    en_title: '3 Learning Modes',
    ja_desc: '問題を1問ずつ確認する演習・本番形式の模試・苦手分野を繰り返すトレーニングで目的別に学習できます。',
    en_desc: 'Exercise mode, full exam simulation, and targeted training — choose the mode that fits your goal.',
  },
  {
    icon: '📊',
    ja_title: '弱点を可視化',
    en_title: 'Track Your Weaknesses',
    ja_desc: 'ドメイン別の正答率グラフで苦手分野を一目で把握。学習の成長記録を積み重ねてスコアアップを実感できます。',
    en_desc: 'Domain-by-domain accuracy graphs reveal your weak spots so you can focus your study where it counts.',
  },
];

export default function Portal() {
  const navigate = useNavigate();
  const { user, loading } = useAuth();
  const { lang, setLang } = useLanguage();
  const { theme, toggleTheme } = useTheme();
  const ja = lang === 'ja';
  const [isMobile, setIsMobile] = useState(window.innerWidth < 768);

  React.useEffect(() => {
    const handler = () => setIsMobile(window.innerWidth < 768);
    window.addEventListener('resize', handler);
    return () => window.removeEventListener('resize', handler);
  }, []);

  // 認証確認中はスピナー
  if (loading) {
    return (
      <div style={{ position: 'fixed', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--color-bg-main)' }}>
        <div className="sherpa-spinner" />
      </div>
    );
  }

  // ログイン済み＆目標資格設定済み → 学習画面へ自動フォワード
  if (user && localStorage.getItem(`targetExam_${user.userId}`)) {
    return <Navigate to="/aws/" replace />;
  }

  const handleStart = () => navigate('/aws/');

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', background: 'var(--color-bg-main)', color: 'var(--color-text-main)', fontFamily: 'inherit' }}>
      <Helmet>
        <title>無限ノック｜AWS認定試験の練習問題サービス</title>
        <meta name="description" content="AWS認定試験（SAA・CLF・SAPなど）の無料練習問題サービス。AI生成の本番同等問題2,600問以上、演習・模試・統計の3本柱でスコアアップをサポート。" />
      </Helmet>

      {/* ── ヘッダー ── */}
      <header style={{
        height: 56, minHeight: 56, background: 'var(--color-bg-white)',
        display: 'flex', alignItems: 'center',
        padding: isMobile ? '0 12px' : '0 var(--spacing-lg)',
        gap: 'var(--spacing-md)', zIndex: 200, flexShrink: 0,
        borderBottom: '1px solid var(--color-border)',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', userSelect: 'none', flexShrink: 0, padding: '0 4px' }}>
          <img
            src={isMobile ? '/mugen-icon.png' : '/mugen-header.png'}
            alt="MugenKnock"
            style={{ height: isMobile ? 32 : 36, width: 'auto', display: 'block' }}
          />
        </div>
        <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 6 }}>
          <button onClick={() => setLang(lang === 'ja' ? 'en' : 'ja')} style={{ background: 'transparent', border: '1px solid var(--color-border)', borderRadius: 'var(--border-radius-md)', cursor: 'pointer', color: 'var(--color-text-sub)', padding: '4px 10px', fontSize: 'var(--font-size-xs)', fontWeight: 700 }}>
            {lang === 'ja' ? 'EN' : 'JA'}
          </button>
          <button onClick={toggleTheme} style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'transparent', border: '1px solid var(--color-border)', borderRadius: '50%', cursor: 'pointer', color: 'var(--color-text-sub)', width: 32, height: 32, padding: 0 }}>
            {theme === 'dark' ? <IconSun /> : <IconMoon />}
          </button>
          <button onClick={() => navigate(user ? '/account' : '/login')} style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', background: user ? 'var(--color-primary-light)' : 'transparent', border: '1px solid var(--color-border)', borderRadius: '50%', cursor: 'pointer', color: user ? 'var(--color-primary)' : 'var(--color-text-sub)', width: 36, height: 36, padding: 0, fontSize: 14, fontWeight: 700 }}>
            {user?.email ? user.email[0].toUpperCase() : <IconUser />}
          </button>
        </div>
      </header>

      {/* ── メインコンテンツ ── */}
      <main style={{ flex: 1, overflowY: 'auto' }}>

        {/* ── ヒーロー ── */}
        <section style={{
          background: 'linear-gradient(160deg, #FF9900 0%, #FF6600 100%)',
          padding: isMobile ? '48px 20px 40px' : '72px 40px 60px',
          textAlign: 'center',
        }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: 'rgba(255,255,255,0.2)', borderRadius: 999, padding: '4px 14px', fontSize: 12, fontWeight: 700, color: '#fff', marginBottom: 20, letterSpacing: '.04em' }}>
            {ja ? '無料で始められる' : 'Free to Start'}
          </div>
          <h1 style={{ fontSize: isMobile ? 26 : 40, fontWeight: 900, color: '#fff', margin: '0 0 16px', lineHeight: 1.25, letterSpacing: '-0.5px' }}>
            {ja ? (
              <>AWS認定試験を<br />本気で合格しよう</>
            ) : (
              <>Pass Your AWS Certification<br />with Confidence</>
            )}
          </h1>
          <p style={{ fontSize: isMobile ? 15 : 17, color: 'rgba(255,255,255,0.9)', margin: '0 auto 32px', maxWidth: 520, lineHeight: 1.7 }}>
            {ja
              ? 'AIが作成した本番同等の練習問題でスキルを磨き、ドメイン別分析で弱点を克服。CLFからProレベルまで全12資格に対応。'
              : 'Practice with AI-generated exam-quality questions, track your progress by domain, and conquer all 12 AWS certifications.'}
          </p>
          <button
            onClick={handleStart}
            style={{
              background: '#fff', color: '#FF6600', border: 'none',
              borderRadius: 999, padding: isMobile ? '14px 32px' : '16px 44px',
              fontSize: isMobile ? 16 : 18, fontWeight: 800, cursor: 'pointer',
              boxShadow: '0 4px 20px rgba(0,0,0,0.15)',
              transition: 'transform 0.15s, box-shadow 0.15s',
            }}
            onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.boxShadow = '0 8px 28px rgba(0,0,0,0.2)'; }}
            onMouseLeave={e => { e.currentTarget.style.transform = 'translateY(0)'; e.currentTarget.style.boxShadow = '0 4px 20px rgba(0,0,0,0.15)'; }}
          >
            {ja ? '学習を始める →' : 'Start Learning →'}
          </button>
          {!user && (
            <p style={{ fontSize: 12, color: 'rgba(255,255,255,0.75)', marginTop: 12 }}>
              {ja ? 'アカウント登録不要で体験できます' : 'No account required to get started'}
            </p>
          )}
        </section>

        <div style={{ maxWidth: 860, margin: '0 auto', padding: isMobile ? '40px 16px' : '60px 32px' }}>

          {/* ── AWS認定取得のメリット ── */}
          <section style={{ marginBottom: isMobile ? 48 : 64 }}>
            <h2 style={{ fontSize: isMobile ? 20 : 26, fontWeight: 800, margin: '0 0 8px', color: 'var(--color-text-main)', letterSpacing: '-0.3px' }}>
              {ja ? 'AWS認定資格を取得するメリット' : 'Why Get AWS Certified?'}
            </h2>
            <p style={{ fontSize: 'var(--font-size-sm)', color: 'var(--color-text-sub)', margin: '0 0 28px', lineHeight: 1.6 }}>
              {ja ? '世界中のエンジニアが目指す、クラウドの国際標準資格です。' : 'The globally recognized standard for cloud professionals worldwide.'}
            </p>
            <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr 1fr' : 'repeat(4, 1fr)', gap: 14 }}>
              {BENEFITS.map((b, i) => (
                <div key={i} style={{
                  background: 'var(--color-bg-white)', border: '1px solid var(--color-border)',
                  borderRadius: 'var(--border-radius-lg)', padding: isMobile ? '16px 12px' : '20px',
                  boxShadow: 'var(--box-shadow-sm)',
                }}>
                  <div style={{ fontSize: isMobile ? 24 : 28, marginBottom: 10 }}>{b.icon}</div>
                  <div style={{ fontSize: isMobile ? 13 : 14, fontWeight: 700, color: 'var(--color-text-main)', marginBottom: 6 }}>
                    {ja ? b.ja_title : b.en_title}
                  </div>
                  <div style={{ fontSize: isMobile ? 11 : 12, color: 'var(--color-text-sub)', lineHeight: 1.6 }}>
                    {ja ? b.ja_desc : b.en_desc}
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* ── このサービスの特徴 ── */}
          <section style={{ marginBottom: isMobile ? 48 : 64 }}>
            <h2 style={{ fontSize: isMobile ? 20 : 26, fontWeight: 800, margin: '0 0 8px', color: 'var(--color-text-main)', letterSpacing: '-0.3px' }}>
              {ja ? '無限ノックでできること' : 'What You Can Do with MugenKnock'}
            </h2>
            <p style={{ fontSize: 'var(--font-size-sm)', color: 'var(--color-text-sub)', margin: '0 0 28px', lineHeight: 1.6 }}>
              {ja ? '合格に必要な3つのアプローチで、スコアを確実に伸ばします。' : 'Three powerful approaches to push your score higher, faster.'}
            </p>
            <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(3, 1fr)', gap: 16 }}>
              {FEATURES.map((f, i) => (
                <div key={i} style={{
                  background: 'var(--color-bg-white)', border: '1px solid var(--color-border)',
                  borderRadius: 'var(--border-radius-lg)', padding: '24px 20px',
                  boxShadow: 'var(--box-shadow-sm)', display: 'flex', flexDirection: 'column', gap: 10,
                }}>
                  <div style={{ fontSize: 32 }}>{f.icon}</div>
                  <div style={{ fontSize: 15, fontWeight: 700, color: 'var(--color-text-main)' }}>
                    {ja ? f.ja_title : f.en_title}
                  </div>
                  <div style={{ fontSize: 13, color: 'var(--color-text-sub)', lineHeight: 1.7 }}>
                    {ja ? f.ja_desc : f.en_desc}
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* ── 対応資格一覧 ── */}
          <section style={{ marginBottom: isMobile ? 48 : 64 }}>
            <h2 style={{ fontSize: isMobile ? 20 : 26, fontWeight: 800, margin: '0 0 8px', color: 'var(--color-text-main)', letterSpacing: '-0.3px' }}>
              {ja ? '全12資格に対応' : 'All 12 AWS Certifications'}
            </h2>
            <p style={{ fontSize: 'var(--font-size-sm)', color: 'var(--color-text-sub)', margin: '0 0 20px', lineHeight: 1.6 }}>
              {ja ? '入門レベルから専門レベルまで、体系的に学習できます。' : 'From foundational to specialty — study at every level.'}
            </p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
              {[
                { code: 'CLF', name: 'Cloud Practitioner', level: ja ? '入門' : 'Found.' },
                { code: 'AIF', name: 'AI Practitioner', level: ja ? '入門' : 'Found.' },
                { code: 'SAA', name: 'Solutions Architect', level: ja ? 'アソシ' : 'Assoc.' },
                { code: 'DVA', name: 'Developer', level: ja ? 'アソシ' : 'Assoc.' },
                { code: 'SOA', name: 'CloudOps Engineer', level: ja ? 'アソシ' : 'Assoc.' },
                { code: 'DEA', name: 'Data Engineer', level: ja ? 'アソシ' : 'Assoc.' },
                { code: 'MLA', name: 'ML Engineer', level: ja ? 'アソシ' : 'Assoc.' },
                { code: 'SAP', name: 'Solutions Architect Pro', level: ja ? 'プロ' : 'Pro' },
                { code: 'DOP', name: 'DevOps Engineer', level: ja ? 'プロ' : 'Pro' },
                { code: 'GAI', name: 'Generative AI Dev', level: ja ? 'プロ' : 'Pro' },
                { code: 'ANS', name: 'Advanced Networking', level: ja ? '専門' : 'Spec.' },
                { code: 'SCS', name: 'Security', level: ja ? '専門' : 'Spec.' },
              ].map(({ code, name, level }) => (
                <div key={code} style={{
                  display: 'inline-flex', alignItems: 'center', gap: 6,
                  background: 'var(--color-bg-white)', border: '1px solid var(--color-border)',
                  borderRadius: 8, padding: '6px 12px',
                }}>
                  <span style={{ fontSize: 13, fontWeight: 800, color: '#FF6600' }}>{code}</span>
                  <span style={{ fontSize: 11, color: 'var(--color-text-sub)' }}>{name}</span>
                  <span style={{ fontSize: 10, color: 'var(--color-text-light)', background: 'var(--color-bg-main)', borderRadius: 4, padding: '1px 5px' }}>{level}</span>
                </div>
              ))}
            </div>
          </section>

          {/* ── 最終 CTA ── */}
          <section style={{ textAlign: 'center', padding: isMobile ? '32px 0' : '48px 0' }}>
            <h2 style={{ fontSize: isMobile ? 20 : 28, fontWeight: 800, margin: '0 0 12px', color: 'var(--color-text-main)' }}>
              {ja ? 'まず目標資格を選ぼう' : 'Pick Your Target Certification'}
            </h2>
            <p style={{ fontSize: 'var(--font-size-sm)', color: 'var(--color-text-sub)', margin: '0 0 24px', lineHeight: 1.6 }}>
              {ja
                ? 'CLF・SAA・SAPなど取得したい資格を選択して学習をスタートできます。'
                : 'Select CLF, SAA, SAP, or any of the 12 certifications and start practicing right away.'}
            </p>
            <button
              onClick={handleStart}
              style={{
                background: 'var(--color-primary)', color: '#fff', border: 'none',
                borderRadius: 999, padding: isMobile ? '14px 32px' : '16px 44px',
                fontSize: isMobile ? 16 : 18, fontWeight: 800, cursor: 'pointer',
                boxShadow: '0 4px 16px rgba(0,0,0,0.12)',
                transition: 'transform 0.15s, box-shadow 0.15s',
              }}
              onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.boxShadow = '0 8px 24px rgba(0,0,0,0.18)'; }}
              onMouseLeave={e => { e.currentTarget.style.transform = 'translateY(0)'; e.currentTarget.style.boxShadow = '0 4px 16px rgba(0,0,0,0.12)'; }}
            >
              {ja ? '資格を選んで学習開始 →' : 'Choose a Cert & Start →'}
            </button>
          </section>

        </div>
      </main>

      {/* ── フッター ── */}
      <footer style={{ padding: '16px var(--spacing-lg)', textAlign: 'center', fontSize: 11, color: 'var(--color-text-light)', borderTop: '1px solid var(--color-border)' }}>
        © {new Date().getFullYear()} MugenKnock
      </footer>

    </div>
  );
}
